### ISSUE TITLE
Divide By Zero in Python Agent 

### ISSUE THREAD

**Issue by FlowerBoss** [s3inlc/hashtopolis#458] opened 2018-09-01 06:07 UTC
- Server Version: 0.7.1
- Client version: 0.1.8
- Hashcat version: 4.2.1
- Task Command: -m500 #HL# wordlist -r rule
- Used "Fix Number of Chunk" when I created new task

**Error :**

![e2](https://user-images.githubusercontent.com/42885065/44942984-d8647600-add2-11e8-890f-3b91f87c3881.png)

**Comment by s3inlc** [comment] 2018-09-03 07:01
Are you able to reproduce it? If yes it would be nice if you could re-run it with debug enabled in the config and paste the output before the division by zero is happening.

**Comment by FlowerBoss** [comment] 2018-09-04 04:39
Sure, I'll do it ASAP,
btw when i set something like 501 (It is not divisible by 10) , It goes on without any problem.


anyway I got this Error after a day when I was Cracking the Cisco MD5,
so it maybe takes time to reproduce it again.
this error is once in a blue moon ^_^

thank you  for your response.

**Comment by FlowerBoss** [comment] 2018-09-04 09:46
hey, I just got the error again and this time by enable debug mode

here UR:

![e4](https://user-images.githubusercontent.com/42885065/45023977-18369200-b04d-11e8-8ad6-1bcdcd222c6c.png)

**Comment by s3inlc** [comment] 2018-09-04 11:31
Ok, the problem causing it to crash definitely is because the length of the chunk is 0, and this should not happen. 
Can you give me some more information on the task, the chunks which currently exist and what benchmark value the agent has?

**Comment by FlowerBoss** [comment] 2018-09-05 04:12
I used a static number of chunk (1000 for 1st test, 501 for 2n test)

and Benchmark is clear on my first post:
7.88MH/S*2 Per Agent 

other issue due to this Error is that after an agent get this , it effects on whole the task.
I hope this will be fix after I edit my agent files .

**Comment by s3inlc** [comment] 2018-09-05 07:15
I would need some numbers of the task:
- keyspace
- benchmark results from hashtopolis (not the speed)
- what is the length of other chunks in this task

Currently I don't see anywhere in the code where it could even happen that the chunk size gets 0.

**Comment by FlowerBoss** [comment] 2018-09-05 10:01
OK
keyspace: 1869011428
benchmark results from hashtopolis: it's not static for me, every time i got new result
length of other chunks in this task: 3730962

any way IDK way you need this 
coz it's diff for other Devices 

but it makes me crazy, just figure it out , I'm working on it as well
thanks

**Comment by s3inlc** [comment] 2018-09-24 14:47
In order to identify the root of this issue. At the point where this zero-size chunks appeared was there any of the agents going offline/crashed/stopped shortly before?

**Comment by Tr4sK** [comment] 2018-09-27 03:26
I have the same issue after hitting twice CTRL+C on the agent.
Now, I’m stuck on that, I need to create a new task to bypasse that issue.

**Comment by s3inlc** [comment] 2018-09-27 07:11
@Tr4sK just as a simple workaround until we are able to fix it. You can delete the chunk with length 0 manually in the database when it occurs then you should be able to continue normally with the task.

**Comment by s3inlc** [comment] 2020-02-11 14:06
This can be closed as the crash is avoided since a longer time and the other issue with ctrl+c should not appear anymore.

**Closed by s3inlc** 2020-02-11 14:06 UTC
Labels: to check on new version

**Comment by Tr4sK** [comment] 2020-06-12 00:32
Thank you :)
