### ISSUE TITLE
Bug: KeyError: 'usePrince' 

### ISSUE THREAD

**Issue by MilzoCSP** [s3inlc/hashtopolis#591] opened 2020-02-05 18:42 UTC
##### Ubuntu 18.04 with CUDA Toolkit

The agent just loops around this error, for modes that i have tested. HC modes: (16800, 16900, 10000, 2500)

It doesn't log the error and deactivate agent either, so ends up in an endless loop.
```
Exception in thread run_loop:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "hashtopolis.zip/htpclient/hashcat_cracker.py", line 253, in run_loop
    if task['files'] and not task['usePrince'] and 1 < self.statusCount < 10 and status.get_util() != -1 and status.get_util() < piping_threshold:
KeyError: 'usePrince'
```
Modes like 0,100,400,500,1500,1700,7400,1420,17200 all checkout fine.

and with mode 16801, I get a different error

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "hashtopolis.zip/__main__.py", line 343, in <module>
  File "hashtopolis.zip/__main__.py", line 222, in loop
  File "hashtopolis.zip/htpclient/hashcat_cracker.py", line 461, in run_benchmark
  File "hashtopolis.zip/htpclient/hashcat_cracker.py", line 545, in run_speed_benchmark
ZeroDivisionError: float division by zero
```
I hope that makes some sense to you
fwiw, I use all hashcat example hashes for tests.

Would be nice if someone else could try and replicate the errors.

**Comment by beecushman** [comment] 2020-02-05 20:25
I can confirm that I've also have had that error using modes 16800 and 2500 with current-dev. I have not tested it with any other modes.

**Comment by s6410** [comment] 2020-02-05 20:47
Can you try force piping? I just had a similar error with a hash from apple secure notes, solved it by checking Use Piping. I’ll check the exact error and post an issue tomorrow.

**Comment by s6410** [comment] 2020-02-05 21:03
Also have you updated the agent? I had to get the agent from devel branch because Prince is called upon in another manner with the devel version of hashtopolis.

**Comment by s6410** [comment] 2020-02-06 06:22
Are you running with or without prince?

**Comment by beecushman** [comment] 2020-02-06 06:29
I tested with the dev branch agent and htp install. No prince, and setting force piping _seemed_ to provide better results with the agent able to continue on without throwing an exception.

**Comment by s6410** [comment] 2020-02-06 06:33
I have tried reproducing the error again but I can't remember what combination of wordlist and rules I ran when it occured. What size of wordlist are you using, kilobytes, and any rules?

**Comment by beecushman** [comment] 2020-02-06 06:38
Pretty small wordlist, ~100,000KB and no rules. I can do a full deploy and run tomorrow if more verbose detail is required.

**Comment by s6410** [comment] 2020-02-06 07:14
This is my setup now:
- Hashtopolis 0.11.0 + 106 (current dev)
- Agent: python 0.5.1
- Hashcat: V5.1.0-1474-gd315f614+

Running in mode 16800 with a wordlist of 130 000KB and no rules I get the same error as @MilzoCSP stated, KeyError: 'usePrince'.

Enforcing piping solves the problem.

**Comment by s3inlc** [comment] 2020-02-06 10:13
Thanks for all your inputs. Based on the stacktrace the first crash case should be fixed now. If someone could verify this and report back, that would be nice.
I still need to do some investigation on the second crash case with mode 16801, it might have to do something with the hash mode.

**Comment by s3inlc** [comment] 2020-02-07 10:22
@MilzoCSP reported that the usePrince crash is fixed now. Also regarding the hash mode 16801, the benchmark reports an error in this case as the input needs to be 64 hex chars and therefore returns a zero. This case is catched now, so that the agent does not crash.
Please re-open the issue, if for any of you there is still something not working regarding these errors.

**Closed by s3inlc** 2020-02-07 10:22 UTC
Labels: bug
