### ISSUE TITLE
Hashlist has too many lines! ?

### ISSUE THREAD

**Issue by kolet** [s3inlc/hashtopolis#485] opened 2018-10-17 22:51 UTC
hey there,
so i tried to upload an hash file , and the error received was "Hashlist has too many lines!
"
the filed i tried to upload was with 10mil hash.

**Comment by kolet** [comment] 2018-10-17 23:10
UPDATE 1
well i tried to minimize the list of 5mil, this time i did not received the error, but it took about 5min untill the web service throw and 505 error, i guess it took to long to update and index the database, after the crash i went to see if any hash was uploaded, and nop, none :)

**Comment by s3inlc** [comment] 2018-10-18 07:11
There is a configurable limit for hashlists (5mil default) to avoid too large imports. If you want you can increase it, but 5 million already is often too much to be imported.
You need to have a powerful server to handle this, the problem is not the webserver, but the mysql server which gives up on such large imports. 
The reason why the numbers are still 0 is because the hashlist numbers only get updated after the import has finished, if it crashes somewhere, they remain 0.

Just in case you didn't knew, we have now a forum (http://hashtopolis.org) which might be better suited for this kind of problem.

**Comment by s3inlc** [comment] 2018-11-05 10:28
This issue seems to be resolved, therefore I'm closing it. Reopen if there is still some problem.

**Closed by s3inlc** 2018-11-05 10:28 UTC
