### ISSUE TITLE
Issue with Electrum Wallet (Salt-Type 4)

### ISSUE THREAD

**Issue by ahvahsky2008** [s3inlc/hashtopolis#620] opened 2020-03-18 19:47 UTC
Cracking freezes on 98.55. Hashcat 5.1 beta
![image](https://user-images.githubusercontent.com/8035828/77001048-5dd65980-696a-11ea-8ff7-fc7c0a0ebebf.png)
![image](https://user-images.githubusercontent.com/8035828/77001082-6595fe00-696a-11ea-9ce2-5b1bd60487c1.png)
![image](https://user-images.githubusercontent.com/8035828/77001093-6b8bdf00-696a-11ea-853a-a2c6086cddd1.png)

hashcat64.exe  --machine-readable --quiet --status --restore-disable --session=hashtopolis --status-timer 5 --outfile-check-timer=5 --outfile-check-dir=..\..\hashlist_19 -o ..\..\hashlists\19.out --outfile-format=1,2,3,4 -p "	" -s 0 -l 11881376 --potfile-disable --remove --remove-timer=5 ..\..\hashlists\19 -a 3 ?l?l?l?l?l?l  --hash-type=21700

**Comment by s3inlc** [comment] 2020-03-18 19:50
Any difference when you run the exact same command manually on the client?

Sometimes hashcat slows down at the end with the progress, as it is finishing the last work elements and it cannot distribute them over the full gpus.

**Comment by ahvahsky2008** [comment] 2020-03-19 11:15
> Any difference when you run the exact same command manually on the client?
> 
> Sometimes hashcat slows down at the end with the progress, as it is finishing the last work elements and it cannot distribute them over the full gpus.

On client same issue

**Comment by ahvahsky2008** [comment] 2020-03-19 17:59
Can you reproduce it on your pc?

**Comment by ahvahsky2008** [comment] 2020-03-19 18:10
17200
21700
21800
not works

**Comment by s3inlc** [comment] 2020-03-19 18:10
No, I can't. 
This clearly is an issue on your client with hashcat (might be driver or something else), which has nothing to do with hashtopolis. If the problem persists, I recommend asking in the hashcat forum, there they might be able to help you.

**Comment by ahvahsky2008** [comment] 2020-03-23 20:41
I found consistent pattern!
When i try solve simple task - all works
```
hashcat64.exe  --machine-readable --quiet --status --restore-disable --session=hashtopolis --status-timer 5 --outfile-check-timer=5 --outfile-check-dir=..\..\hashlist_19 
-o ..\..\hashlists\19.out --outfile-format=1,2,3,4 -p "	" -s 0 -l 456976 --potfile-disable --remove --remove-timer=5 ..\..\hashlists\19 -a 3 ?l?l?l?l?l  --hash-type=21700 
```

But when i send harder - its freeze on 98.88 percentage
`hashcat64.exe  --machine-readable --quiet --status --restore-disable --session=hashtopolis --status-timer 5 --outfile-check-timer=5 --outfile-check-dir=..\..\hashlist_19 -o ..\..\hashlists\19.out --outfile-format=1,2,3,4 -p "	" -s 0 -l 11881376 --potfile-disable --remove --remove-timer=5 ..\..\hashlists\19 -a 3 ?l?l?l?l?l?l  --hash-type=21700 
`

**Comment by s3inlc** [comment] 2020-07-10 12:26
So from what I see, it hangs when you give it a larger chunk work. Does it also happen when you run the command manually with the specific -s and -l values?
If yes, then this must be something connected to hashcat, either caused by a bug there or an issue with the driver or a broken driver installation.

**Comment by winxp5421** [comment] 2021-01-02 19:11
Closing this issue. If you feel this has been done in error please reopen and update us why

**Closed by winxp5421** 2021-01-02 19:11 UTC
