### ISSUE TITLE
REJECTED - hash (WPA)

### ISSUE THREAD

**Issue by xecommatos** [s3inlc/hashtopolis#302] opened 2017-11-23 19:54 UTC
Hey,

Just spotted an issue with the validation of HCCAPX.

Code:
STATUS  6       SPEED   356851  1000    628980  1000    642719  1000    EXEC_RUNTIME    53.137896 50.224800        48.889287       CURKU   0       PROGRESS        819200  11881376        RECHASH 1 1RECSALT 1       1       TEMP    65      61      56      REJECTED        0
{"action":"solve","token":"YNUWMX7qQQ","chunk":545,"keyspaceProgress":0,"progress":819200,"total":11881376,"speed":1628550,"state":5,"cracks":["\u001b[33mTo fix, run this command:\u001b[0m","1a5fadf0517af0e631757a244ef5c8fd:84a8e41ca21a:c83a35f89628:Nikolic:aleksandar"]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":1,"zaps":[]}
Progress:  6.89% | Speed:1.63MH/s | Cracks:2    | Accepted:0    | Zapped:0    | Queue:1
Finished processing chunk

Client Version 0.46.2
Hashcat version v4.0.0 found
Hashtopussy: commit 4a85a04 branch master 0.4.3

Am I doing something wrong ?

**Comment by s3inlc** [comment] 2018-01-22 20:45
I was not able to reproduce this. I'm not completely sure what happened, I have not enough informations about the task and the hashlist, but it's not normal that it sends two cracks (it's clear that one is just a warning message, but anway) and then just says skipped 1 instead of 2.
If you still can reproduce the error it would be nice to get some additional information, otherwise please report if it appears again.

**Comment by winxp5421** [comment] 2018-05-03 14:12
I will be closing this issue if you feel this issue was closed in error please re-open and explain why.

**Closed by winxp5421** 2018-05-03 14:12 UTC
Labels: bug, incomplete information
