### ISSUE TITLE
Agent not passing Cracked Hashes to Server

### ISSUE THREAD

**Issue by 64nickel** [s3inlc/hashtopolis#206] opened 2017-06-13 20:35 UTC
Current Server version:  0.3.2.
Current Client version:  0.43.13
The exact task command you are trying to run:  #HL# 00.txt
    (if native hashcat:  hashcat64 -m 2100 DCC2_hashes.txt -a 0 00.txt)
Problem Description:  Agent is cracking DCC2 hashes, but is not passing that information back to the server.  Server still shows yellow bar, 0 hashes cracked, after job completes.

Debug output from the client by running "hashtopussy.exe debug":

Client Version 0.43.13
Checking for client updates
{"action":"update","type":"csharp","version":"0.43.13"}
{"action":"update","response":"SUCCESS","version":"OK"}
You are using the latest client version
System is Windows
Existing token found
{"action":"login","token":"ceLJOah9YB"}
{"action":"login","response":"SUCCESS","timeout":"30"}
Logged in to server
{"action":"download","type":"hashcat","token":"ceLJOah9YB","force":0}
Hashcat version v3.6.0 found
Getting task
{"action":"task","token":"ceLJOah9YB"}
{"action":"task","response":"SUCCESS","task":27,"attackcmd":"#HL# 00.txt","cmdpars":" --hash-type=2100","hashlist":6,"bench":30,"statustimer":5,"files":["00.txt"],"benchType":"run","hashlistAlias":"#HL#"}
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"ceLJOah9YB","hashlist":6}
Getting chunk...
{"action":"chunk","token":"ceLJOah9YB","taskId":27}
{"action":"chunk","response":"SUCCESS","status":"keyspace_required"}
Server has requested the client to measure the keyspace for this task
{"action":"keyspace","token":"ceLJOah9YB","taskId":27,"keyspace":733976}
Getting chunk...
{"action":"chunk","token":"ceLJOah9YB","taskId":27}
{"action":"chunk","response":"SUCCESS","status":"benchmark"}
Server requsted the client benchark this task for 30 seconds
{"action":"bench","token":"ceLJOah9YB","taskId":27,"type":"run","result":"1"}
{"action":"bench","response":"SUCCESS","benchmark":"OK"}
Getting chunk...
{"action":"chunk","token":"ceLJOah9YB","taskId":27}
{"action":"chunk","response":"SUCCESS","status":"OK","chunk":20,"skip":0,"length":733976}
C:\Users\Admin\Desktop\MRAP-Agent\hashcat\hashcat64.exe   --hash-type=2100 "C:\Users\Admin\Desktop\MRAP-Agent\hashlists\6"  00.txt --outfile-check-dir="C:\Users\Admin\Desktop\MRAP-Agent\hashlists\zaps6"  --potfile-disable --quiet --restore-disable --session=hashtopussy --status --machine-readable --status-timer=5 --outfile-check-timer=5 --remove --remove-timer=5 --separator=: -s 0 -l 733976
STATUS  2       SPEED   324     1       324     1       327     1       323     1       EXEC_RUNTIME    3.408591
3.424890        3.392343        3.409846        CURKU   0       PROGRESS        5268024 16881448    RECHASH     2
24      RECSALT 2       23      TEMP    47      51      50      48      REJECTED        187151
{"action":"solve","token":"ceLJOah9YB","chunk":20,"keyspaceProgress":0,"progress":5268024,"total":16881448,"speed":1298,"state":2,"cracks":["$DCC2$10240#MASKED_USER1#4f75a84b2c3acb878e3ae2d9def60c61:pass@w0rd","$DCC2$10240#MASKED_USER2#837369cf2921ec6f3fb9bfc8b9eab3d9:Welcome3"]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress: 31.21% | Speed:1.30MH/s | Cracks:2    | Accepted:0    | Zapped:0    | Queue:1
STATUS  2       SPEED   324     1       323     1       326     1       323     1       EXEC_RUNTIME    3.409713
3.429730        3.377310        3.405169        CURKU   0       PROGRESS        11800575        16881448        RECHASH
3       24      RECSALT 3       23      TEMP    47      51      51      49      REJECTED        187151
{"action":"solve","token":"ceLJOah9YB","chunk":20,"keyspaceProgress":0,"progress":11800575,"total":16881448,"speed":1296,"state":2,"cracks":["$DCC2$10240#MASKED_USER3#e098509e3489df1a73f1d2d997efc6f6:Happy123"]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress: 69.90% | Speed:1.30MH/s | Cracks:1    | Accepted:0    | Zapped:0    | Queue:1
STATUS  4       SPEED   324     1       323     1       326     1       323     1       EXEC_RUNTIME    3.415380
3.426183        3.391273        3.421347        CURKU   0       PROGRESS        16881448        16881448        RECHASH
3       24      RECSALT 3       23      TEMP    47      50      47      48      REJECTED        187151
Attack finished
{"action":"solve","token":"ceLJOah9YB","chunk":20,"keyspaceProgress":0,"progress":16881448,"total":16881448,"speed":1296,"state":4,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:100.00% | Speed:1.30MH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1
Finished processing chunk
Getting chunk...
{"action":"chunk","token":"ceLJOah9YB","taskId":27}
{"action":"chunk","response":"SUCCESS","status":"fully_dispatched"}
Getting task

**Comment by winxp5421** [comment] 2017-06-13 21:18
Looks like the agent is picking the cracks up but, maybe the server is not matching properly? Just a first guess. Can you give us a screen shot of the uncracked hashes in the hash list as seen in the HTP webui and if it's possible an example of how the hash list looks in the SQL table. Thanks.

**Comment by 64nickel** [comment] 2017-06-14 14:42
I'll work on getting those today or tomorrow.

**Comment by 64nickel** [comment] 2017-06-14 15:07
Attached.  I masked out usernames.  The lines with the red dot at the end are the ones that the agent cracked but did not report back to the server.
![dcc2-hashes-in-hashtopussy](https://user-images.githubusercontent.com/8929451/27139629-24c8d7fe-50e9-11e7-92af-4bf2c94e1b16.jpg)
![dcc2-in-database](https://user-images.githubusercontent.com/8929451/27139630-24d88820-50e9-11e7-80c7-3cbf01248cb0.jpg)

**Comment by 64nickel** [comment] 2017-06-16 14:38
UPDATE:  Been doing some more testing.  I created two copies of my wordlist and two copies of my hashlist. One copy has been unix2dos'd, the other dos2unix'd.  I removed everything from ZAPS folder and all files from the agent.  Removed all hashlists and wordlists from the server and uploaded the aforementioned files.  I'm using rockyou.txt from Kali as my wordlist source.  The agent now reports on the following two hashes back to the server consistently so that's good:

$DCC2$10240#MASKED_USER1#4f75a84b2c3acb878e3ae2d9def60c61:pass@w0rd
$DCC2$10240#MASKED_USER2#837369cf2921ec6f3fb9bfc8b9eab3d9:Welcome3

However, hashcat still cracks this one but doesn't report back:

$DCC2$10240#MASKED_USER3#e098509e3489df1a73f1d2d997efc6f6:Happy123

I've gone so far as to manually create a new hashlist with only this one item in it, and a new wordlist with only Happy123 in it.  When the agent runs this simple job, it still cracks with hashcat but agent does not forward up.  I still see "Progress: 100.00% | Speed:0.00KH/s | Cracks:1 | Accepted:0 | Zapped:0 | Queue:1" after it finds the word.

**Comment by winxp5421** [comment] 2017-06-16 16:03
This issue is an interesting one. I want to tank you for being persistent and keeping us updated. I'll try and reach out to s3in!c and get a solution out.

**Comment by 64nickel** [comment] 2017-06-16 16:29
NP. Let me know if you need me to set up additional tests.

**Comment by blazer2x** [comment] 2017-06-16 17:01
Since the agent is showing cracked 1 it is picking up the crack. You are able to see it in the json post string. The accepted:0 means the sever is not matching this hash up with the hashlist. It appears to be a server side isse

**Comment by winxp5421** [comment] 2017-06-16 17:06
that was my first thought that maybe the hashes where somehow malformed or possibly the server was looking for a salt ( user selected hashes are salted when you are not salted [separately]) but his screenshots look good. @64nickel maybe grab packets and have a look at the actual JSON data coming into the server for us?

**Comment by 64nickel** [comment] 2017-06-16 18:19
Apache logs don't have any detail; had to do packet capture.  Here is the part where my agent sent the cracked password and the server's response.

![capture1](https://user-images.githubusercontent.com/8929451/27239413-725049d6-5296-11e7-8a24-70f8927d8b82.JPG)

**Comment by winxp5421** [comment] 2017-06-16 18:30
huh, again I don't see anything immediately wrong with this I'm starting to think its a problem with how the server matches the "hash".

Again thank you so much for troubleshooting with us.

**Comment by 64nickel** [comment] 2017-06-16 18:41
Are there any backend logs I can pull besides webserver logs?  Is there a server debug functionality?  Anything you want me to pull from the database?

**Comment by winxp5421** [comment] 2017-06-16 18:45
You can enable php errors in the config file ( that's the only server debug ) and server side logs are still in development.  Currently I can't think of anything in the db that we would need however please make a backup just in case we can't reproduce the problem on our own systems.

**Comment by winxp5421** [comment] 2017-06-16 18:46
Whoops did not mean to post and close.

**Comment by winxp5421** [comment] 2017-06-16 18:55
/src/inc/load.php `ini_set("display_errors", "0");` > `'ini_set("display_errors", "1");`

you can try to use a curl'like the application to pass the same data the client is sending to see if the server reports any odd errors, Though currently, I don't have exact commands you could run to achieve this.

Beware this may leak sensitive data depending on what errors are invoked.

**Comment by winxp5421** [comment] 2017-06-16 18:59
though now that I'm thinking about it realistically any PHP errors should be logged in the webserver/PHP log

**Comment by 64nickel** [comment] 2017-06-16 19:07
Nothing in the access.log nor error.log that looks relevant.  A whole lot of POST /api/server.php and GET /get.php?file=#.....  Nothing about details of the hash/cracked password to or from anything in these logs.

**Comment by winxp5421** [comment] 2017-06-16 19:11
If i had to guess the client is indeed sending the cracked hashes to the server but the server is not matching the hash to the hash stored in the database correctly. so it is just dropping the unmatched as it does not know what to do with it. why this is happening with dcc2 specifically I have no idea. just my 2 cents based on info you have provided. we will test and push out a fix as soon as our dev is free to do so.

**Comment by 64nickel** [comment] 2017-06-16 19:14
Same here.  Other DCC2s in the same hashlist using the same wordlist are reporting back fine.  

I'll leave you guys to your work.  However, I would be interested to know if you are able to duplicate it on your end at any point during your troubleshooting and testing.

**Comment by winxp5421** [comment] 2017-06-16 19:16
That right there is the strangest part, why some are fine and other are not.. seems strange.

**Comment by 64nickel** [comment] 2017-06-16 19:53
No worries.  After next Wed I'm in the same boat until about mid August.  I'll check in here periodically to touch base as time permits.

**Comment by s3inlc** [comment] 2018-03-19 09:48
As this issue is sitting here for more than half a year and there was a huge code change since, I close this issue now. I suspect that this issue was related to the salt separator issue.

If the issue still persists with the newest version, please reopen.

**Closed by s3inlc** 2018-03-19 09:48 UTC
Labels: bug, to check on new version

**Comment by spcqike** [comment] 2020-01-24 06:31
hello,

i just wanted to give an update.
i recently needed to crack an DES salted key (mode 14000), and the result wasn't transfered to the server.

if anyone likes to test it himself, you can use this keypair
d931f92e0475753e:aabbccddee112233
the result should be found within the first 0.02%, nearly instant, and should be 73e0b9616e616e61.
i used [#HL# -a 3 -1 DES_full.charset --hex-charset ?1?1?1?1?1?1?1?1 -w 3] as command. as you see, you'll need a DES_full.charset.
