### ISSUE TITLE
[dev branch] Health check, invalid health check id

### ISSUE THREAD

**Issue by TheWorkingDeveloper** [s3inlc/hashtopolis#550] opened 2019-03-10 22:48 UTC
Health check requested by server!
Retrieving health check settings...
Starting check ID 2
Error on sending health check results: {'message': 'Invalid health check id!', 'action': 'sendHealthCheck', 'response': 'ERROR'}

This ID does exist and is assigned to the client.
Please note this is on the current-dev branch.

**Comment by s3inlc** [comment] 2019-03-12 18:09
Can you please re-produce the error with debug logging enabled to get more information?

**Comment by s3inlc** [comment] 2019-07-12 07:42
The issue is fixed on the current-dev branch.

**Closed by s3inlc** 2019-07-12 07:42 UTC
Labels: bug
