### ISSUE TITLE
Chatbot not working with Slack/Teams

### ISSUE THREAD

**Issue by jasongraf** [s3inlc/hashtopolis#443] opened 2018-08-22 03:26 UTC
- Your current Server version located at the bottom of any Hashtopolis webpage.
Hashtopolis: commit 59384bb branch xxxx_database_mod 0.5.1 
- Current Client version
Not Applicable
- Your current Hashcat version
Not Applicable
- The exact task command you are trying to run.
I am trying to get the chatbot notification running with Slack and Teams
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
Not applicable

**Describe your problem in as much detail as possible " It's broke " is not a description.**

I have added a webhook URL for both Slack and Teams to my notifications under My Account. The notification seems to create properly, but I am not getting any messages. I can't identify anywhere this is being logged. I did run a manual curl command to POST to the web hook from the server and it posted into both Slack and Teams fine. Can you point me in the right direction to further troubleshoot the lack of messages?

**Comment by s3inlc** [comment] 2018-08-22 07:04
Thanks for opening a separate issue.
What did you enter as receiver when creating the notification? How did the curl command look you issued manually and which worked?

**Comment by jasongraf** [comment] 2018-08-22 13:05
Here is the URL I entered for the receiver in the notification setup for Teams. I redacted the specific path info as it is sensitive.
https://outlook.office.com/webhook/<secretpath>/IncomingWebhook/<secretpath>/<secretpath>

Here is the curl command I tested and worked from server.

curl -X POST -H 'Content-type: application/json' --data '{"text":"I am alive and trying to talk to you."}' https://outlook.office.com/webhook/<secretpath>/IncomingWebhook/<secretpath>/<secretpath>

**Comment by s3inlc** [comment] 2018-08-22 13:13
Did you check that there were no requests incoming to your slack? Because I'm pretty sure that it sends them, but I think the problem is because Slack is expecting a different format. The Notification sent by the Chatbot looks following (and is just sent as a normal POST request, not directly json):

`payload={"username": "Hashtopolis", "text": "Example test notification"}`

If you want to adjust this yourself, you would just need to change the way the curl request is made here: https://github.com/s3inlc/hashtopolis/blob/master/src/inc/notifications/NotificationChatBot.class.php#L15

**Comment by jasongraf** [comment] 2018-08-22 13:26
So it looks like this?

curl -X POST '{"text":"I am alive and trying to talk to you."}' https://outlook.office.com/webhook/secretpath/IncomingWebhook/secretpath/secretpath

**Comment by s3inlc** [comment] 2018-08-22 13:28
No, I think like this:
`curl -X POST 'payload={"text":"I am alive and trying to talk to you."}' `

**Comment by jasongraf** [comment] 2018-08-22 13:44
Ok, so the below curl works without the "-H 'Content-type: application/json" pieces, but it does need the "--data" command. It also does NOT like the "payload=" part.

curl -X POST --data '{"text":"I am alive and trying to talk to you."}'

Feel like helping me with the PHP changes? I hate to ask. If you can't, I will learn something in the process :).

**Comment by jasongraf** [comment] 2018-08-22 13:50
What do you think of this? I removed "payload=" from $data and added "--data" to "    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST --data");"

<?php
class HashtopolisNotificationChatBot extends HashtopolisNotification {
  protected     $receiver;
  public static $name = "ChatBot";
  function getTemplateName() {
    return "notifications/chatbot";
  }
  function getObjects() {
    return array();
  }
  function sendMessage($message, $subject = "") {
    $username = APP_NAME;
    $data = "" . json_encode(array(
          "username" => $username,
          "text" => $message
        )
      );
    $ch = curl_init($this->receiver);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST --data");
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $result = curl_exec($ch);
    curl_close($ch);
    return $result;
  }
}
HashtopolisNotification::add('ChatBot', new HashtopolisNotificationChatBot());

**Comment by hops** [comment] 2018-08-22 14:20
It should work if you replace this:
```
    $data = "payload=" . json_encode(array(
          "username" => $username,
          "text" => $message
        )
      );
```
with:
```
  $data = json_encode(array("text" => $message));
```
Slack doesn't seem to allow setting another username and also doesn't like the `payload` "prefix".

**Comment by jasongraf** [comment] 2018-08-22 14:37
Ok, I currently have this: This is not working either.

`<?php

class HashtopolisNotificationChatBot extends HashtopolisNotification {
  protected     $receiver;
  public static $name = "ChatBot";
  
  function getTemplateName() {
    return "notifications/chatbot";
  }
  
  function getObjects() {
    return array();
  }
  
  function sendMessage($message, $subject = "") {
    $username = APP_NAME;
    $data = json_encode(array("text" => $message));
    
    $ch = curl_init($this->receiver);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $result = curl_exec($ch);
    curl_close($ch);
    
    return $result;
  }

$NOTIFICATIONS['ChatBot'] = new HashtopolisNotificationChatBot();`

On a similar note, when I add a notification item in My Account, the task create page does not finish and goes to a blank white page. The task creates, but I am thinking something in the notification code is hanging. This is even with NO modifications to the code.

**Comment by s3inlc** [comment] 2018-08-22 14:55
The code looks fine to me now, but as you are saying it's hanging always there must be something other being wrong anyway. Have you checked the apache2 error log after such a blank page?

**Comment by jasongraf** [comment] 2018-08-22 15:58
Here is the error from the log: it says curl_init is not defined.

[Wed Aug 22 11:48:50.364375 2018] [:error] [pid 25436] [client REDACTEDIP:60016] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/hashtopolis/src/inc/notifications/NotificationChatBot.class.php:19\nStack trace:\n#0 /var/www/html/hashtopolis/src/inc/notifications/Notification.class.php(156): HashtopolisNotificationChatBot->sendMessage('New Task <http:...', 'Hashtopolis on ...')\n#1 /var/www/html/hashtopolis/src/inc/handlers/NotificationHandler.class.php(66): HashtopolisNotification->execute('newTask', Object(DataSet), Object(DBA\\NotificationSetting))\n#2 /var/www/html/hashtopolis/src/inc/handlers/TaskHandler.class.php(284): NotificationHandler::checkNotifications('newTask', Object(DataSet))\n#3 /var/www/html/hashtopolis/src/inc/handlers/TaskHandler.class.php(111): TaskHandler->create()\n#4 /var/www/html/hashtopolis/src/tasks.php(32): TaskHandler->handle('createTask')\n#5 {main}\n  thrown in /var/www/html/hashtopolis/src/inc/notifications/NotificationChatBot.class.php on line 19, referer: http://REDACTED/tasks.php?new=true

**Comment by s3inlc** [comment] 2018-08-22 16:14
You're missing the `php-curl` package then. This is listed in the server's prerequisites.

**Comment by jasongraf** [comment] 2018-08-22 17:55
Ok, you were right. I had it working, but I went back and tried the original code, and now I am having fits with this. I went back and copied over the 0.5.1 Notification files. The server will not load, and is giving this error.

[Wed Aug 22 13:52:07.969646 2018] [:error] [pid 1368] [client REDACTED:41372] PHP Fatal error:  Uncaught Error: Call to undefined method HashtopolisNotification::add() in /var/www/html/hashtopolis/src/inc/notifications/NotificationChatBot.class.php:27\nStack trace:\n#0 /var/www/html/hashtopolis/src/inc/load.php(43): require_once()\n#1 /var/www/html/hashtopolis/src/api/server.php(10): require_once('/var/www/html/h...')\n#2 {main}\n  thrown in /var/www/html/hashtopolis/src/inc/notifications/NotificationChatBot.class.php on line 27

**Comment by jasongraf** [comment] 2018-08-23 04:37
@s3inlc  you can ignore my message above. I got things all messed up and winded up having to start the server from scratch. In the end it will be better, as it is on current version. I think I had some mismatched code. 

Ultimately, this little bit of code was the winner. $data = json_encode(array("text" => $message));

Placing that in NotificationChatBot.class.php did the trick and is now working. 

Is there a better way to handle this modification? I assume your original code was good for some system. Can I create a type for Slack/Teams that this code will work for?

**Comment by s3inlc** [comment] 2018-08-23 06:58
Yes, the Chatbot notification was originally made to work with Mattermost. I think the cleanest way would be just to add a new notification type for Slack/Teams. Feel free to do a PR for such a notification type.

**Comment by s3inlc** [comment] 2018-08-31 09:52
As the original poster was providing the code which was working and we didn't get a feedback on this so far, I close this issue. The Slack notification is included in the newest release, please reopen if there is any issue with using it.

**Closed by s3inlc** 2018-08-31 09:52 UTC
